# Generated by Django 5.2.11 on 2026-03-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_product_slug_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
