# Generated by Django 5.2.11 on 2026-03-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
    ]
