# Generated by Django 5.2.11 on 2026-03-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='template_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
