# Generated by Django 5.2.11 on 2026-03-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='template_name',
        ),
    ]
