# Generated by Django 5.2.11 on 2026-03-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
