# Generated by Django 5.2.11 on 2026-06-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_orderitem_color_orderitem_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
