# Generated by Django 5.2.11 on 2026-06-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_orderitem_custom_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='custom_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
