# Generated by Django 5.2.11 on 2026-06-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_orderitem_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
